### ISSUE TITLE
どのような手段で提言されるのか

### ISSUE THREAD

**Issue by iwamatsu0430** [cto-a/policy-proposal#14]
提言について質問です。
こちらはどのような手順、手続きでデジタル庁創設のステークホルダーへと届けられるのでしょうか。

提言手段について明記されていないよう見受けられたのですが、然るべき人の元へ届かなければ実効性に懸念が出てしまうのではないかと僭越ながら疑問に感じました。
もし、このような手段を講じている、もしくはその予定がある。または公開する事はできないが対応しているといった事であればお教えいただく事は可能でしょうか。

ちなみに[各府省への意見・要望フォーム](https://www.e-gov.go.jp/help/seisaku/)および[首相官邸のご意見・ご感想フォーム](https://www.kantei.go.jp/jp/forms/goiken_ssl.html)ともに2000字の制限があり、
こちらから投稿される訳ではないのだろうと邪推したため、本質問を投げさせていただきました。
(本提言が https://github.com/cto-a/policy-proposal/commit/386316c5c6029134b79c8a66a1add94f66f903cd 現在4000字を超えているため)

どうぞよろしくお願いいたします。

**Comment by kentaro** [comment]
ご質問ありがとうございます！

CTO協会では、公開されている活動としても、理事が経産省やIPAの委員をやっていたり、政治・経済における各種アクター（政治家や経済団体等）との協議・連携を行っていたりします。そのため、取り得る手段を幅広く用いて、提言の実効性をもたせられるような届け方を実践していくつもりです。

**Comment by iwamatsu0430** [comment]
ご回答ありがとうございます。

実効性についてご配慮されているとの事、承知いたしました。デジタル庁創設において本提言が実際に考慮される事を期待しております。
あらためて、ご対応ありがとうございます。
