### ISSUE TITLE
「コンピューターが働きやすい社会」という文言について

### ISSUE THREAD

**Issue by Songmu** [cto-a/policy-proposal#15]
言わんとすることはわからないでもないですが、違和感を覚えました。ITから遠い人が見るとぎょっとするのではないかと思います。「提言」なので、引っかかりのある文言を散りばめるのは必要だと思いますが、この文言はどちらかというと、反発を生んでしまうのではないでしょうか。

「人間とコンピューター」という二項対立で捉える人は多いと思うので、これだと、人間よりもコンピューターを大事にするように思われてしまいかねないと思います。

もちろんそれは本意ではないはずなので、「まずは人間ありきでそのためにコンピューターの活用が必要」だという当たり前の大前提のスタンスを明らかにすべきだと思います。そうしないとCTO協会自体が「よくわからないサイバー集団」というふうに思われてしまう危険性があります。

#13 に的確な指摘があることに気が付きましたが、まずは我々のスタンスがどのようなものであり、読み手が誰なのか、そことのギャップを意識して書いたほうが良いのではないでしょうか。

代案なく、言いっぱなしで申し訳ないですが。

**Comment by kentaro** [comment]
確かに、前提がわからないまま「コンピューターが働きやすい社会」なる文言が出てくると、おっしゃるような懸念があるなと思いました。一方で、CTO協会という「よくわからない」集団がインパクトのある提言をするには、我々にしかない観点と表現を用いることもまた必要であると思います。

なので、その文言を変える必要はないと僕は思いますが、ご提案の通り「まずは人間ありきでそのためにコンピューターの活用が必要」という前提を感じ取ってもらう必要はあると思いました。ただ、人間の幸福追求がだいじと最初にいっているので、それ以上にいうとくどい気もします。

**Comment by bateleurX** [comment]
「コンピューターが働きやすい社会」というのはたしかにおかしいと感じました。
人間が主でコンピューターは従であることが大前提とすると「コンピューターを働かせやすい社会」になるのでしょう。コンピューターは主体的に活動できません。

**Comment by kentaro** [comment]
お感じになったことも最もではあると思います。修辞的な表現であるとお考えいただけるとよいかもしれません。

**Comment by kentaro** [comment]
ワーキンググループでの議論の結果、 #31 において、「[「コンピューターに仕事をさせやすい社会」「より人が価値を生む活動に集中できる社会」](https://github.com/cto-a/policy-proposal/blob/master/digital-agency/proposal.md)」という表現に変更いたしました。ご意見をいただきましてありがとうございました！
