### ISSUE TITLE
提言の主体と修正提案の帰属先について

### ISSUE THREAD

**Issue by ymotongpoo** [cto-a/policy-proposal#16]
GitHubを利用しているので、提言の文章に対して修正の提案を行うことは可能ですが、変更分に対してそれが誰に帰属するものなのかが一切明らかになっていません。ライセンスの設定もしくは意見の帰属先をCTO協会にする旨の同意が必要なのではないでしょうか。
誤字脱字等の修正なのであれば大した違いはないことではあると思いますが、広く意見を求めることを想定しているのであれば、この点を明らかにしない限り、オープンソースに対する理解がある人間の意見は期待できないのではないでしょうか。

**Comment by kentaro** [comment]
おっしゃる通りだと感じました。意見のようなもので帰属先を明示するプロトコルとして、なにかいい例をご存じないでしょうか？

**Comment by ymotongpoo** [comment]
逆に質問ですが、このままPRを受け付けたとして、どう扱うおつもりだったのでしょうか。

**Comment by ymotongpoo** [comment]
一般的なOSSであれば著作物の譲渡に関する同意を得るのが一般的です。
https://producingoss.com/ja/copyright-assignment.html

しかしながら今回は修正対象が「提言」であり単に著作物としてだけでなく、その主体になる可能性もあります。集めた意見をどう扱い、最終的に誰の意見とするのか、そうしたガバナンスを明らかにするようなものがあればよいのではないでしょうか。

**Comment by kentaro** [comment]
> 逆に質問ですが、このままPRを受け付けたとして、どう扱うおつもりだったのでしょうか。

本文内に文責を明示している文章に取り込むわけですから、（すくなくてとも「つもり」としては）その文責のもとに公表された文書として扱うこととになります。また、文書の作成に関わった事自体はGitおよびGitHubの機能としての履歴に残ることになりますね。

> 集めた意見をどう扱い、最終的に誰の意見とするのか、そうしたガバナンスを明らかにするようなものがあればよいのではないでしょうか。

明示されている方がされていないよりも相対的によいことは確かではありそうですね。文面が難しそうですが、考えてみます。

**Comment by kentaro** [comment]
私もこのあたりについてよく知っているわけではないので簡単に調べてみたところ、[オープンソースの法的側面 | Open Source Guides](http://opensource.guide/ja/legal/#%E7%A7%81%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%A7%E3%81%AF%E8%BF%BD%E5%8A%A0%E3%81%AE%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%82%BF%E3%83%BC%E3%82%A2%E3%82%B0%E3%83%AA%E3%83%BC%E3%83%A1%E3%83%B3%E3%83%88%E3%81%8C%E5%BF%85%E8%A6%81%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B)という文書を見つけました。それによると、GitHubを使っているこのリポジトリについては、（もしライセンスが明示されているならば）コントリビューターは同じライセンスを適用することに同意するという規約になっているようです。

そのため我々に必要なのは、

* ライセンスを
* 「提言」の主体はあくまでも文書の文責にあること

を明示することにあるのではないかと整理することができました。m

**Comment by kentaro** [comment]
ライセンスについては↑の通りpull reqestを出しました。

**Comment by kentaro** [comment]
「コントリビューションに関するポリシーについて記載する #28 」を元に、日本CTO協会で会員のみなさまを広く募った上で組成したワーキンググループにおいて議論をした結果、承認いただきました。この内容で本イシューでのご提案が解決できているのではないかと思いますが、いかがでしょうか？

**Comment by ymotongpoo** [comment]
#18 同様、 #28 で明確にされたと思います。本件解決したと思いますのでクローズいたします。ご対応ありがとうございました。

**Comment by kentaro** [comment]
ご質問・ご提案ありがとうございました！
