### ISSUE TITLE
質問: 提言の主体について

### ISSUE THREAD

**Issue by ymotongpoo** [cto-a/policy-proposal#18]
#16 に関連しますが、修正に関するものではありませんのでIssueを分けます。

[デジタル庁の創設に向けての提言](https://github.com/cto-a/policy-proposal/blob/74577a317f5a6e6483499d066ad8d55c4fb7064b/digital-agency/proposal.md)において、提言を行っているのは「日本CTO協会理事一同」となっておりますが、一方で[レポジトリのREADME](https://github.com/cto-a/policy-proposal/blob/74577a317f5a6e6483499d066ad8d55c4fb7064b/README.md)には「一般社団法人日本CTO協会による提言」とあります。

これについて以下の質問があります。

1. この「デジタル庁の創設に向けての提言」を総意でなく、わざわざ理事一同にとどめる理由は何でしょうか
2. 区別されている場合、レポジトリの大元にある「一般社団法人日本CTO協会による提言」はどのような場合に行われるのでしょうか

**Comment by kentaro** [comment]
ご質問ありがとうございます。

1. 法人の「総意」を決めるプロセスは自明ではありません。そのため、本提言に関しては、明示的に同意をいただけるスコープに限ってだしております。
2. 2.については、しかるべき手続きが確立した後、必要に場合に行われることもあり得るのだと思います。

**Comment by ymotongpoo** [comment]
いまいただいた回答を整理すると

- CTO協会には現状明示的に総意を得るガバナンス機構はないが、今回は理事のみの同意で公開した

と読み取れますが、そういうことなのでしょうか。

**Comment by kentaro** [comment]
違います。法人としての理事会による決議という公式のプロセスはもちろん存在していまし、弁護士に監事としてはいってもらってもいます。

一方で、CTO協会の「総意」といった場合、たとえば会員の大多数の賛成を得るというプロセスを経た意見が「総意」という意味であるという解釈も容易に成り立ちます。そのため、「法人の「総意」を決めるプロセスは自明ではありません」といいました。

ご意見をいただくのはありがたいですが、憶測で悪意のある風説を広めるのはおやめください。
https://twitter.com/ymotongpoo/status/1314509045378605056

**Comment by ymotongpoo** [comment]
「理事会による決議」が総意でなく、「総意として公開するプロセスがない」のであれば

> CTO協会には現状明示的に総意を得るガバナンス機構はないが、今回は理事のみの同意で公開した

ということに他ならないと思いますが。「総意を得るガバナンス機構」は解釈の問題ではなく「『日本CTO協会の提言』という形式で公開をする際の会としての承認プロセスの存在」のことを指しています。

また「悪意」と書いていますが、私が「ガバナンスが緩い」と書いたのは、そもそも「総意を取るプロセスも自明ではない」状態を指していますし、「確認を取る必要がある」のは必要性があることを指しているので、それを勝手に「悪意」と解釈されるほうに「悪意」感じます。正しく運用されるべきことだと思っているので、それを妨げる発言ととらえられます。

**Comment by kentaro** [comment]
> 「総意を得るガバナンス機構」は解釈の問題ではなく「『日本CTO協会の提言』という形式で公開をする際の会としての承認プロセスの存在」のことを指しています

その定義にもとづいていえば、先に述べたとおり「法人としての理事会による決議という公式のプロセスはもちろん存在しています」。

一方で、「総意」という言葉を上記に引用した定義のみ限定して用いているのではないということは先にも述べました。にも関わらず、自らの定義のみに基づいて一方的に「ガバナンスが緩い」ということを「悪意」ではないとするならば、それはいかなる語によって表現されるべき心的状態であるといえばよいのでしょうか？

**Comment by ymotongpoo** [comment]
回答ありがとうございます。次の解釈で合っていますか。

-『一般社団法人日本CTO協会の提言』（および協会としての公な発言）は理事会の決議のみで決定でき、理事以外の参加者の承認を必要としない 。これは規約や会則に記載された公式なプロセスである。

まずこの部分からクリアにさせてください。

**Comment by kentaro** [comment]
ご質問の内容については、本件とは関係のない内容であると思われます。また、詳細については私の能力に余る問題であるので回答できません。

**Comment by ymotongpoo** [comment]
いえ、まさに本件の一番重要な部分です。「一般社団法人日本CTO協会の提言」と書かれるのであれば、理事以外の参加者も含めた承認があるものと解釈するのが普通だと思います。それを「理事会のみの決議で決定できる」のかどうかはガバナンスの問題です。

こういう回答を含めて「ガバナンスの問題だ」と言っているのです。回答できないのであればそれで構いません。以上です。

**Comment by kentaro** [comment]
そもそも提言の文責は「一般社団法人日本CTO協会」ではないので関係のない内容であると申し上げました。

一方で、お感じになった事実につきましては当方での不足があったと思いますので、改善していきたいと思います。ご意見ありがとうございました。

**Comment by ymotongpoo** [comment]
話をそらしてばかりいるようですが質問の内容は「文責が誰か」ではなく「提言の主体は誰か」です。

https://github.com/cto-a/policy-proposal/issues/18#issuecomment-706133666
こちらの回答を踏まえると「文責＝協会理事一同、主体＝協会」ということですね。大元の質問も回答頂き理解いたしました。ご回答ありがとうございました。

**Comment by y-matsuwitter** [comment]
#16 および #18 双方に対するコメントになりますが、改善すべき点が多々あると認識しており、指摘非常に感謝しております。継続して対応させていただきますので今後もご意見いただけると幸いです。

**Comment by kentaro** [comment]
#16 同様、 #28 で解決できているのではないかと思いますが、いかがでしょうか？

**Comment by ymotongpoo** [comment]
#28 拝見しました。質問した内容が明確になり、納得いたしました。本件は解決したと思いますので、クローズいたします。

**Comment by kentaro** [comment]
ご質問・ご提案ありがとうございました！
