### ISSUE TITLE
用語の整理と改善について

### ISSUE THREAD

**Issue by keiji** [cto-a/policy-proposal#19]
同じ代名詞で違う主体を指している箇所は、それぞれ何を指しているのか明示した方が良いかと思いました。
たとえば、「私たち」を例に取ると、最初の段落の中で「私たち」が3回出てきます。

```
デジタルトランスフォーメーション（DX: Digital Transformation）は、業務効率向上を目的とするデジタル化だけを意味するのではありません。完全自動化が目指しやすい労働集約な業務をコンピューターに任せることで、人間しかできない本質的なことに私たちが集中できるように変革することを意味しています。行政におけるDXとは、行政サービスをデジタル化することによる効率化であるとともに、その質的な転換であるべきだと私たちは考えます。すなわち、我が国に関わるすべての人々が人間としての幸福を追求することを可能にするための取り組みこそ、私たちが真に必要としているDXなのです。
```

「本質的なことに私たちが集中できるように」「質的な転換であるべきだと私たちは考えます。」「私たちが真に必要としているDXなのです。」

1つ目は「人間」を、2つ目は「日本CTO協会」を指していることはわかります。しかし、3つ目の私たちが「人間」を指しているのか、それとも「日本CTO協会」を指しているのかがはっきりとはわかりませんでした。この時点で、真のDXを必要としているのが人間か、CTO協会かがぶれてしまうと、その後の提言の受け取り方も大きく変わってくると考えます。

----
```
今後も継続して人々の健康で文化的な暮らしを実現するためには、「**コンピューターが働きやすい社会**」を実現することが必要です。
```

一つの文に「実現」が二回使われているのが気になりました。例えばですが、一つ目を「維持」に変えて、「今後も継続して人々の健康で文化的な暮らしを維持するためには、」とするのはどうでしょうか。

また「**コンピューターが働きやすい社会**」についての違和感は他の方も指摘していますが、社会というと範囲が広すぎ、用途からすると「社会基盤」と限定する方が誤解が少ないと感じました。

「少子化と高齢化による人口（労働力減少）に対してDXを進めていかないといけないね。特に「行政のDX」を進めていくためには、コンピューターが働きやすい社会基盤の実現が不可欠だよね」ということなんだと理解しています。
その上で、最初の段落で「DX」と「行政のDX」について触れてしまっているので、この段落での解説が省略された結果、論理が飛躍したと受け取られる場合があるのだとと考えます。

ここはわかりやすさを優先して、頭に「我が国では、世界中のどの国もまだ経験したことのない少子高齢化と人口減少が加速しています」を移動させて、「DX」の実現が必要と言う前提を、読者に提示しておくのはどうでしょうか。

```
我が国では、世界中のどの国もまだ経験したことのない少子高齢化と人口減少が加速しています。今後も継続して人々の健康で文化的な暮らしを継続するためには、「**DX（デジタルトランスフォーメーション）**」を実現することが必要です。

デジタルトランスフォーメーション（DX: Digital Transformation）は、業務効率向上を目的とするデジタル化だけを意味するのではありません。完全自動化が目指しやすい労働集約な業務をコンピューターに任せることで、人間しかできない本質的なことに私たちが集中できるように変革することを意味しています。行政におけるDXとは、行政サービスをデジタル化することによる効率化であるとともに、その質的な転換であるべきだと私たちは考えます。すなわち、我が国に関わるすべての人々が人間としての幸福を追求することを可能にするための取り組みこそ、私たちが真に必要としているDXなのです。

行政におけるDXを実現するためには「**コンピューターが働きやすい社会基盤**」の整備が必要です。
```

----

```
日本CTO協会では、これらを「2つのDX」と呼び、切っても切り離せない車輪の両軸であると考えます。
```

言いたいことは理解できます。その上で、「車輪の両軸」より「一対の車輪」とか「車の両輪」の方が意図が伝わりやすいと思いました。

----

```
いまの社会はコンピューターが働きやすい社会であるとはとてもいえません。それはすなわち、私たち人間にとっても幸福を追求する権利から疎外されているということに他なりません。
```

「それはすなわち…他なりません」の一文は取ってしまった方が意味がつながりやすいと思います。この段落だけ微妙に修飾……というか「気持ちがこもりすぎているな」と感じました。

たとえば「はんこや紙の書類など過去の儀礼的な慣習に基づく非生産的な活動を強いられています。」という文も「はんこや紙の書類など非生産的な活動を強いられています。」とか「はんこや紙の書類など慣習を強いられています。」などでも意味は通じるわけで、文章の要素はなるべく少なくした方が読み手の負荷が減って良いかと思います。

----

```
我が国では、少子高齢化と人口減少とによって、労働力はますます減っていきます。一方で、コンピューターはますます安価になっていきます。いまこそ、人々の幸せのために、デジタル技術を活用するべきです。
```

この部分は論理の飛躍があると感じました。

「人々の幸せのため」というのは、最初の段落にあったDXにより人間がしなくてもいい非生産的な労働をする必要がなくなった結果として、もっと人間的な幸福を追求できるようになるという話で、そのことはすぐ後の文にも出てくるのですが……。
A-B-Cのある論理のものがA-C-Bと来ると、読み手の認知負荷が高くなるので、あまり奇をてらわず、順序立てて展開した方がわかりやくて良いと思います。

----

```
日本CTO協会は、そのような職能を持つCTOたちが集い切磋琢磨する中で、知見を集積してきた組織です。真のDXの実現のために、私たちがお役に立てるものと考えます。
```

「真のDX」とは、最初の段落にあった「私たちが真に必要としているDX」のことと思います。最初の段落も
「私たちが必要としている『真のDX』なのです。」と用語を合わせた方が良いかと思います。

----

*ここまでレビューしたところで時間が切れになったので、また時間が取れたらコメントとかで追加するかもしれません。*

**Comment by kentaro** [comment]
ありがとうございます！確かにその通りだと思われるご指摘が含まれていると思います。取り込みを検討します！

**Comment by kentaro** [comment]
文意に変更を及ぼさない程度の小さな変更ではない内容のイシューやPull Requestでいただいたご提案について、取り込みにポリシーを定めようとしておりますので、いましばらくお待ち下さい 🙏

**Comment by kentaro** [comment]
大変おまたせしました。上記コメントで書いたとおり、コントリビューションの取り込みの扱いについて議論していました。
→ コントリビューションに関するポリシーについて記載する #28

@keiji さんのご提案につきまして、上記のポリシーにご同意いただけるか否かについてまずお尋ねしたく、ご検討をお願いできますでしょうか？

その上で、ご同意いただけました場合、現在CTO協会で組成したワーキンググループで勧めている提言の新バージョンとの整合について検討させていただければと思います。

どうぞ、よろしくお願いします。

**Comment by keiji** [comment]
提示いただいたコントリビューションポリシーに合意します。

**Comment by kentaro** [comment]
ご回答ありがとうございます！しかしながら、せっかくたくさんの貴重なご意見をいただいたにも関わらず、十分には検討できなかったことをお詫びいたします。 

https://github.com/cto-a/policy-proposal/issues/13#issuecomment-716327016 で記載した通りのイベントもありまして、日本CTO協会の理事およびワーキンググループ内で検討を行い、提出したバージョンを既に作成済みの状況です。

https://github.com/cto-a/policy-proposal/blob/master/digital-agency/proposal.md

結果としていただいた内容を取り込めた部分も多くあるのではないかと思います。重ね重ね、ありがとうございました。

**Comment by keiji** [comment]
こちらこそ返答が遅くなり申し訳ありませんでした。
このIssueについてはcloseします。

日本CTO協会の皆様の活動に感謝しています。
