### ISSUE TITLE
ソフトウェアファーストな法整備について

### ISSUE THREAD

**Issue by megascus** [cto-a/policy-proposal#23]
「現行の法令ファーストではなく、ソフトウェアファーストに思考し」というのは現行の法令を無視してというように受け取れるので、法治国家に住んでいる身としては受け入れられません。
前段にも書いてあるように法整備(ルール)が前提で、それに則って社会の仕組み(実装)を直していくべきですので、文章の見直しをお願いいたします。

**Comment by kentaro** [comment]
ご意見ありがとうございます。

「前段にも書いてあるように法整備(ルール)が前提で、それに則って社会の仕組み(実装)を直していくべき」というご理解に同意します。現行の法令を無視してよいという主張ではないということでご理解ください。

**Comment by megascus** [comment]
ご理解くださいという話ではなくて、だれでも誤解の無いように書き直しましょうという話です。
立場の違う人に誤解の無いように伝える気はないという認識をしました。
そのような形ですとこれ以上この提言に価値を見出せないのでクローズします。
