### ISSUE TITLE
取り込まれる可能性のあるIssue/prの種類に関して

### ISSUE THREAD

**Issue by achiku** [cto-a/policy-proposal#26]
公開ありがとうございます。国政と国民が行政のデジタルサービス化に大きな関心を寄せているタイミングでの提言、タイムリーだと思いました。自分も国民として、ソフトウェアエンジニアとして効率的に行政がデジタルサービスを活用できるようになっていくことを望んでいます。

1点質問したいことがございます。こちらのIssueで議論し、提言に取り込まれる可能性のある指摘の種類に関してですが、大きく分けて(a)textlint設定/ライセンス/当該リポジトリ運営方法の修正、(b)提言の趣旨は変更せずタイポ、ニュアンスやフレーズが持つ印象を修正、(c)提言内にある5つの項目自体、もしくはその内容に対する修正、があると思っています。こちらの分類で申しますと、どの領域の指摘が提言に取り込まれる可能性があるものでしょうか。

背景として、(a)や(b)に関しては既に有益な指摘があり取り込まれている認識なのですが ( #8、#17 )、(c)に関してどういうスタンスでこちらのリポジトリを公開しているのかがわからず戸惑っております(もちろん(b)と(c)を完全に切り離すのは難しいのですが.....)。

[こちらのツイート](https://twitter.com/kentaro/status/1314363015106498560)では(c)に関係のある事に関しては各自のブログにて書く事が望ましいという指摘があり、実際に[CTO協会のデジタル庁創設にかかる提言について](https://zenn.dev/taichi/articles/4466467200c5448436c5)というブログも出てきておりますが、リポジトリのスタンスとして(c)は各自のブログで議論するべきという方針が団体内に存在するのであれば、このリポジトリで受け付ける指摘は(a)(b)であるというスタンスを明示した方がIssueを上げやすくなるかと思っております。

**Comment by kentaro** [comment]
明快な整理、ありがとうございます！

(c)に関して、お示しのツイートは言葉足らずでした。「ブログ等で」と書いたのは、(c)のような内容を前提となる議論抜きでいきなりpull requestで行うのは難しい（コントリビュートしてくれる方へご負担をおかけする）だろうと思い、ブログ等でまず議論するとよいのではないかという意図でした。なので、このリポジトリのイシューで議論するのでもよかろうと思います。

その上で、(c)のような議論を取り込んだ際の、提言の主体や文責の問題について #18 で議論した結果、改善をはかる余地があるということになりましたので、(c)についての取り扱いのポリシーについてはその結果をお待ちいただければと思います。

**Comment by achiku** [comment]
承知いたしました。 #18 が解決し、(c)に対するポリシーが確定しましたらこちらのIssueもクローズしてください。

**Comment by achiku** [comment]
ご連絡ありがとうございます。以下のコントリビューションポリシーに関して確認しました。

- https://github.com/cto-a/policy-proposal/blob/22deb6d6e47e91ea3296e8476130630972bad619/CONTRIBUTING.md

(1)(2)(3)のカテゴリ別にどこまで提案がなされるべきで、どのようなプロセスを経て反映され得るのか明確になっている為、当イシューはクローズで問題ございません。

以下は提案なのですが、(3)についても提案/議論をGitHub上オープンに受け付けるというのであれば、是非この5つの項目に至った背景、理由部分も含めてオープンであると議論がしやすいと感じており、ワーキンググループ等でなされた議論が読める状態になっていると嬉しいです。

例えば自分が見る事が多い一般社団法人キャッシュレス推進協議会では[このような](https://www.paymentsjapan.or.jp/wordpress/wp-content/uploads/2020/06/roadmap2020.pdf)形で議論や進むべき方向性がどのように導出されており、どのようなスケジュールで検討を進めていくか等がオープンになっております。もちろん「(3)に関しては理念のようなものの為、議論の必要性は低い」という話もそれはそれでありかと思っているのですが、オープンであり且つ議論を受け付けるというスタンスを取るのであれば、(もちろんCTO協会様側のリソース制約もあろうとは思いますが)、可能な限り議論の過程やなぜこの5つの項目を重要視しているのか等含めてオープンになっていると、より生産的な議論ができると感じております。ご検討よろしくお願いいたします。

**Comment by kentaro** [comment]
建設的なご提案、ありがとうございます！おっしゃる通りリソースの問題もありますが、できる範囲でできるだけオープンにやっていければと思います。ありがとうございました。
